sonar.projectKey=KrishnaXplore_Civic_reporting_system
sonar.organization=krishnaxplore
sonar.projectName=Civic Reporting System
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
