# Generated by Django 5.2.6 on 2025-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visa_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
