apiVersion: v1
kind: ConfigMap
metadata:
  name: civic-config
data:
  CLIENT_URL: "https://civic-reporting-system-two.vercel.app"
  SERVER_URL: "https://civic-reporting-system-rfyn.onrender.com"
  ML_SERVICE_URL: "http://civic-ml-svc:8000"
  NODE_ENV: "production"
  PORT: "5000"
  JWT_EXPIRE: "7d"
